services:
  realtime-chat-db:
    image: postgres:17-alpine
    container_name: realtime-chat-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "0.0.0.0:5436:5432"
    volumes:
      - realtime_chat_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro

  realtime-chat-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime-chat-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - realtime-chat-db
    ports:
      - "0.0.0.0:7722:8000"


volumes:
  realtime_chat_pgdata:
    name: realtime_chat_pgdata


