services:
  realtime-chat-db:
    image: postgres:17-alpine
    container_name: realtime-chat-db
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - realtime_chat_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    command: ["postgres", "-p", "5436"]

  realtime-chat-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtime-chat-api
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      - realtime-chat-db
    command: ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "7722"]

volumes:
  realtime_chat_pgdata:
    name: realtime_chat_pgdata
